export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const FETCH_TYPE_PRODUCT = "FETCH_TYPE_PRODUCT";
export const FETCH_PRODUCT_BY_TYPE = "FETCH_PRODUCT_BY_TYPE";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const ADD_CART = "ADD_CART";
export const DELETE_CART = "DELETE_CART";
export const NUMBER_QUANTITY = "NUMBER_QUANTITY";
export const FETCH_TYPE_COMBO_PRODUCT = "FETCH_TYPE_COMBO_PRODUCT";
export const FETCH_COMBO_BY_LINK = "FETCH_COMBO_BY_LINK";
export const FETCH_DETAIL_COMBO = "FETCH_DETAIL_COMBO";
export const FETCH_SUPPLIER_TYPE = "FETCH_SUPPLIER_TYPE";
export const FETCH_PRODUCT_SUPPLIER_BY_TYPE = "FETCH_PRODUCT_SUPPLIER_BY_TYPE";
export const FETCH_DETAIL_SUPPLIER = "FETCH_DETAIL_SUPPLIER";

//admin

export const ADD_TYPES = "ADD_TYPES";
export const DELETE_TYPES = "DELETE_TYPES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_TYPES_COMBO = "ADD_TYPES_COMBO";
export const DELETE_TYPES_COMBO = "DELETE_TYPES_COMBO";
export const ADD_TYPES_SUPPLIER = "ADD_TYPES_SUPPLIER";
export const DELETE_TYPES_SUPPLIER = "DELETE_TYPES_SUPPLIER";
export const FETCH_PRODUCT_SUPPLIER = "FETCH_PRODUCT_SUPPLIER";
export const ADD_PRODUCT_SUPPLIER = "ADD_PRODUCT_SUPPLIER";
export const UPDATE_PRODUCT_SUPPLIER = "UPDATE_PRODUCT_SUPPLIER";
export const DELETE_PRODUCT_SUPPLIER = "DELETE_PRODUCT_SUPPLIER";
export const FETCH_PRODUCTS_TO_ORDERS = "FETCH_PRODUCTS_TO_ORDERS";
export const FETCH_PRODUCTS_COMBOS = "FETCH_PRODUCTS_COMBOS";
